name: SpringJ
channels:
  - javascript
dependencies:
  - python=3.10
  - bokeh=2.4.2
  - conda-forge::numpy=1.21.*
  - nodejs=16.13.*
  - flask
  - pip
  - pip:
    - Flask-Testing
    - streamlit==1.18.1
    - numpy==1.24.1
    - pandas==1.5.3
    - plotly==5.13.0
    - scipy==1.10.0
    - streamlit-lottie==0.0.3
    - streamlit-extras==0.2.6
    - scipydirect==1.4